services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql-nlw
    environment:
      MYSQL_DATABASE: db_events
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    networks:
      - rede_local
networks:
  rede_local:
    driver: bridge