spring:
  application:
    name: Events - API
  datasource:
    username: ${MYSQL_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:mysql}
    url: jdbc:mysql://localhost:3306/db_events
  jpa:
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
